input_aa = 'MHNFICLCEHVSCNEFTGSPLFMPAKLWFDIWQYDLYSSSMDHTSGMGTSQAHASQWPPDLVLSGQKKIQDIMKQMVLIWRCTGCKCIVIMVMWWELNVWMCRFICKHMDEFQRMCQCGNVCCRAITEWWHERAWMLFRILGKKANSSCCMAIERCNWERGNFNKCSRKRACTCYLLRSVYKWREDKGMDARRIWSRFNHSLWMGYSHMFEKIPSVAFGLRRVHECCHLFAWSWCMMGMRCNTDHEVSGGCFSVGLLMEFRTYGDEDFCRWRMTLYHDMYGCRLIVRFSTPKSHVNDPMILANKMWDPCAELCVNNKVLTVIIPMFMIEEVVCVFGAHDYGGYETNFYNLDGATRWKQIRDVQKAHYDPPGEFTRTKAWDALMRCVCHVDWAAMDKPGSRRRTPMTEIRFRAIFSCTRLQGHMFNENSTRHDFYCTNGEISQLALQCFKSKSGFDDRLFAQANNTIVPSVIQPKHPCVNEETGVQPLNEHQLDHNNYMVTGWDILLEIRPCTWIWTYSYDTHMKYFDGRKWYKSPDVSHCKRTAFEVSYYKTTWWNINATYYVQCKNEIHRMPVQTLMVFKYHCDANSADAYFIFFPWTDKLMHTFDENMASKEGFPGWLPDTVYDRVDHLPGTYFIHMTDRGTEDSHKWKELLHAHEFQKLQMAEATTNCLDVWRRLETPDDQPLREHEHDFRDYWHNIRIPLPRETPPMASMTEVHDWLYASCRTIVEFTERKKQPSVGHCRIANIYEGMFTFYQVFYMNWIQWDHWYSTKERPCHTKCRLCHWHNWWCMHRDFVLMLTWTCTRPEEFVWSTIMEFTQINYPCHRQSEVSTKCQEMQGKWTIPQIKIICGPICRGRHLKPSLKDCCEPYNHQATYYCYLATWLQLRMAMHRNLKNWSHAFCRSESNKPNDNYLWDWRMGRHVRIKWPETMILLMKLSRMVWSDYESCSKALRQAMGPGKSWNIKGSFEGVVYCASEMWTTKHHNDLMYIRFVSCATY' + '*'

codon_dict = {
	'A': ['GCG', 'GCC', 'GCA', 'GCT'],
	'C': ['TGC', 'TGT'],
	'D': ['GAT', 'GAC'],
	'E': ['GAA', 'GAG'],
	'F': ['TTT', 'TTC'],
	'G': ['GGC', 'GGT', 'GGG', 'GGA'],
	'H': ['CAT', 'CAC'],
	'I': ['ATT', 'ATC', 'ATA'],
	'K': ['AAA', 'AAG'],
	'L': ['CTG', 'TTA', 'TTG', 'CTT', 'CTC', 'CTA'],
	'M': ['ATG'],
	'N': ['AAC', 'AAT'],
	'P': ['CCG', 'CCA', 'CCT', 'CCC'],
	'Q': ['CAG', 'CAA'],
	'R': ['CGT', 'CGC', 'CGG', 'CGA', 'AGA', 'AGG'], 
	'S': ['AGC', 'TCT', 'AGT', 'TCC', 'TCA', 'TCG'],
	'T': ['ACC', 'ACG', 'ACT', 'ACA'],
	'V': ['GTG', 'GTT', 'GTC', 'GTA'],
	'W': ['TGG'],
	'Y': ['TAT', 'TAC'],
	'*': ['TAA', 'TGA', 'TAG']
}

total = 1

for i in input_aa:
    total *= len(codon_dict[i])

print(total % 1000000)